import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AttemptService } from '../../services/attempt/attempt.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-instruction-page',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './instruction-page.component.html',
  styleUrl: './instruction-page.component.scss'
})
export class InstructionPage {
  private attemptService = inject(AttemptService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  public agreed = signal<boolean>(false);
  public isStarting = signal<boolean>(false);

  public handleStartExam() {
    if (!this.agreed()) return;

    this.isStarting.set(true);
    // Assume the ExamSetId was passed in the URL (e.g., /user/instructions/1c3a...)
    const examSetId = this.route.snapshot.paramMap.get('id');

    if (examSetId) {
      this.attemptService.startAttempt(examSetId).subscribe({
        next: (res) => {
          this.isStarting.set(false);
          // Navigate to the exam page using the new AttemptId generated by SQL Server
          this.router.navigate(['/examination', res.attemptId]);
        },
        error: (err) => {
          this.isStarting.set(false);
          alert('Failed to start the exam: ' + err.message);
        }
      });
    }
  }
}