// <auto-generated />
using System;
using ExamPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamPortal.Infrastructure.Migrations
{
    [DbContext(typeof(ExamPortalDbContext))]
    [Migration("20260513094706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamPortal.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuestionSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AnswerOp__3214EC07202807D0");

                    b.HasIndex(new[] { "QuestionSetId" }, "IX_AnswerOptions_QuestionSetId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ExamAtte__3214EC07E6731D39");

                    b.HasIndex("ExamSetId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("SecretToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__ExamSets__3214EC07C42C9423");

                    b.HasIndex(new[] { "TenantId" }, "IX_ExamSets_TenantId");

                    b.ToTable("ExamSets");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.InstructionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("AgreementRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ExamSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Instruct__3214EC075309B5E7");

                    b.HasIndex(new[] { "ExamSetId" }, "UQ__Instruct__03D28BA435D00C5E")
                        .IsUnique();

                    b.ToTable("InstructionSets");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.QuestionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07B537FBB9");

                    b.HasIndex(new[] { "ExamSetId" }, "IX_QuestionSets_ExamSetId");

                    b.ToTable("QuestionSets");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Tenants__3214EC071CFE9784");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0790B1D544");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "Email", "TenantId" }, "IX_Users_Email_Tenant")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__UserAnsw__3214EC070F84E405");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.QuestionSet", "QuestionSet")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnswerOptions_QuestionSets");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.ExamSet", "ExamSet")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamSetId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_ExamSets");

                    b.HasOne("ExamPortal.Domain.Entities.User", "User")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamAttempts_Users");

                    b.Navigation("ExamSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamSet", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ExamSets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExamSets_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.InstructionSet", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.ExamSet", "ExamSet")
                        .WithOne("InstructionSet")
                        .HasForeignKey("ExamPortal.Domain.Entities.InstructionSet", "ExamSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstructionSets_ExamSets");

                    b.Navigation("ExamSet");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.QuestionSet", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.ExamSet", "ExamSet")
                        .WithMany("QuestionSets")
                        .HasForeignKey("ExamSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionSets_ExamSets");

                    b.Navigation("ExamSet");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.User", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("ExamPortal.Domain.Entities.ExamAttempt", "Attempt")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAnswers_ExamAttempts");

                    b.HasOne("ExamPortal.Domain.Entities.QuestionSet", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAnswers_QuestionSets");

                    b.HasOne("ExamPortal.Domain.Entities.AnswerOption", "SelectedOption")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAnswers_AnswerOptions");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.AnswerOption", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.ExamSet", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("InstructionSet");

                    b.Navigation("QuestionSets");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.QuestionSet", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ExamSets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExamPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("ExamAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
